steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/[PROJECT_ID]/webapp:v1", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/[PROJECT_ID]/webapp:v1"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=[KUBERNETES_CONFIG_FILE]
  - --image=gcr.io/[PROJECT_ID]/webapp:v1
  - --location=[LOCATION]
  - --cluster=[CLUSTER]
